In [248]:
import numpy as np
import matplotlib.pyplot as plt
import sparse_matrix_lib

In [235]:
N=10

In [236]:
b= np.random.rand(N)

In [237]:
A = np.random.rand(N,N)

In [238]:
As = sparse_matrix_lib.sparseMatrix(1,1)
As.construct(A)

In [239]:
so_buoc_lap = 6
lb = np.linalg.norm(b)

q = [b/lb]
v = q[0]
H = []
for i in range(1, so_buoc_lap):
    v = As.mul_vector(v)
    h_col = np.zeros(i+1)
    for j in range(0,i):
        do_dai_hinh_chieu = v.dot(q[j])
        h_col[j]       =   do_dai_hinh_chieu
        v                 = v - q[j]*do_dai_hinh_chieu
    remain = np.linalg.norm(v)
    h_col[i] = remain
    H.append(h_col)
    if(remain <1e-12):
        print("Full")
        break
    v/=remain
    q.append(v)


In [240]:
H

[array([3.53794983, 2.30620794]),
 array([1.95336653, 0.60309586, 1.17479272]),
 array([0.41320017, 0.24363615, 0.49878037, 0.9853694 ]),
 array([-0.75028322, -0.54965341, -0.2805709 , -0.27593956,  0.57877366]),
 array([-0.05590768,  0.18542119,  0.08406129, -0.32081456, -0.16412929,
         0.88389538])]

In [241]:
def rotate(x_old, y_old):
    r = np.sqrt(x_old*x_old + y_old*y_old)
    c = x_old/r
    s = y_old/r
    if x_old>0:
        return [-c, s]
    else:
        return [c, -s]

In [242]:
def rotate_action(x,y, goc):
    [c1,s1] = goc
    x_new = x*c1 -y*s1
    y_new = x*s1 + y*c1
    return [x_new,y_new]

In [243]:
v = np.zeros(5)
v[0],v[1] = rotate_action(5,0, rotate(5,0))
v

array([-5.,  0.,  0.,  0.,  0.])

In [244]:
angle =[]
for i in range(0, so_buoc_lap-1):
    goc = rotate(H[i][i], H[i][i+1])
    angle.append(goc)
    H[i][i], H[i][i+1] = rotate_action(H[i][i], H[i][i+1], goc)
H

[array([-4.22323148e+00, -2.22044605e-16]),
 array([ 1.95336653, -1.32055387,  0.        ]),
 array([ 0.41320017,  0.24363615, -1.10441601,  0.        ]),
 array([-0.75028322, -0.54965341, -0.2805709 ,  0.64118764,  0.        ]),
 array([-0.05590768,  0.18542119,  0.08406129, -0.32081456,  0.89900471,
         0.        ])]

In [245]:
angle[3][0]**2 + angle[3][1]**2

1.0

In [255]:
be1 = np.zeros(N)
be1[0] = np.linalg.norm(b)
for i in range(1, 5):
    goc = angle[i-1]
    be1[i-1], be1[i] = rotate_action(be1[i-1], be1[i], goc)
be1

array([-1.68767349, -0.50241829, -0.44199464, -0.37578164, -0.78818894,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])