In [54]:
import numpy as np
import matplotlib.pyplot as plt
import sparse_matrix_lib

from mpl_toolkits.mplot3d import Axes3D

In [55]:
N=3
A = np.random.rand(N,N)

In [56]:
np.linalg.matrix_rank(A)

3

In [57]:
b = np.random.rand(N)


In [58]:
A_old = A 

In [59]:
v = []
for i in range(0,N):
    x = A[i:N, i]
    e1 = np.zeros(N-i)
    e1[0] = np.linalg.norm(x)
    cur = np.sign(x[0]) * x + e1
    cur = cur/np.linalg.norm(cur)
    for j in range(i,N):
        old_col = A[i:N, j]
        new_col = old_col - 2 * cur* np.dot(cur, old_col)
        A[i:N, j] = new_col 
    v.append(cur)
    

In [60]:
b_old = b

In [61]:
v

[array([0.91508876, 0.3586982 , 0.18425027]),
 array([0.99847904, 0.05513269]),
 array([1.])]

In [64]:
for i in range(0, N):
    b_con = b[i:N]
    new_b_con = b_con - 2 * v[i] * np.dot(v[i], b_con)
    b[i:N] = new_b_con

In [66]:
x_old = np.linalg.solve(A_old, b_old)
x_old

array([-1.33298671,  1.41402014,  0.36270462])

In [69]:
def solve_triangle_matrix(A,b):
    n = len(b)
    x = np.zeros(n)
    for i in range (n-1,-1,-1):
        x[i] = b[i]
        for j in range(i+1, n):
            x[i] -= x[j]* A[i,j]
        x[i] = x[i]/A[i,i]
    return x

In [70]:
solve_triangle_matrix(A,b)

array([-1.33298671,  1.41402014,  0.36270462])