In [654]:
import numpy as np
import sparse_matrix_lib

In [655]:
N=4
b= np.random.rand(N)
b_old = b
A = np.random.rand(N,N)
A = np.transpose(A).dot(A)

In [656]:
As = sparse_matrix_lib.sparseMatrix(1,1)
As.construct(A)

In [657]:
A

array([[2.29873254, 2.36335325, 1.49701171, 1.92849247],
       [2.36335325, 2.72668716, 1.34667528, 2.13964398],
       [1.49701171, 1.34667528, 1.38516613, 1.28737007],
       [1.92849247, 2.13964398, 1.28737007, 1.98403093]])

In [658]:
so_buoc_lap = N+1

x = []
p = []
r = []
x.append(np.zeros(N))
p.append(b)
r.append(b)
for i in range(1, so_buoc_lap):
    v = As.mul_vector(p[i-1])
    step_length = r[i-1].dot(r[i-1])/(p[i-1].dot(v))
    x.append(x[i-1] + step_length*p[i-1])
    r.append(r[i-1] - step_length*v)
    beta = (r[i].dot(r[i]))/(r[i-1].dot(r[i-1]))
    p.append(r[i] + p[i-1]*beta)


In [659]:
r

[array([0.42943083, 0.25220092, 0.95405685, 0.71612399]),
 array([-0.38792109, -0.58881384,  0.35377191, -0.03132676]),
 array([-0.12845487,  0.04186248, -0.05873452,  0.14053543]),
 array([-0.02133343,  0.02571364,  0.01765312, -0.01978129]),
 array([-8.74949418e-13, -9.37538241e-13, -5.81437676e-13, -7.94250082e-13])]

In [660]:
np.dot(r[0], r[1])

-7.979727989493313e-17

In [661]:
p[0].dot(A.dot(p[1]))

1.5265566588595902e-16

In [662]:
def CG_solve(A,b):
    so_buoc_lap = N+1
    er = 1e-12
    x = []
    p = []
    r = []
    x.append(np.zeros(N))
    p.append(b)
    r.append(b)
    for i in range(1, so_buoc_lap+1):
        v = A.dot(p[i-1])
        step_length = r[i-1].dot(r[i-1])/(p[i-1].dot(v))
        x.append(x[i-1] + step_length*p[i-1])
        r.append(r[i-1] - step_length*v)
        if(np.linalg.norm(r[-1]) < er):
            return x[i]
        beta = (r[i].dot(r[i]))/(r[i-1].dot(r[i-1]))
        p.append(r[i] + p[i-1]*beta)
    return x[-1]

In [663]:
N=10
A=np.random.rand(N,N)
b=np.random.rand(N)
A = np.transpose(A).dot(A)
x = CG_solve(A,b)
A.dot(x) - b

array([ 2.48233656e-11, -1.33584255e-11, -3.46052076e-11,  1.92039717e-11,
        1.59917635e-11,  1.14124266e-11,  2.20775620e-11, -3.27842198e-11,
       -2.25551799e-11,  7.32092165e-12])