In [722]:
import numpy as np

In [723]:
N = 4
A = np.random.rand(N,N)

In [724]:
while(np.linalg.matrix_rank(A)!=N):
    A = np.random.rand(N,N)

In [725]:
A_old = A

In [726]:
A[:,[2,0]] = A[:,[0,2]]


In [727]:
A

array([[0.38164107, 0.5969474 , 0.08686001, 0.92176969],
       [0.51311101, 0.85904722, 0.46971943, 0.04818951],
       [0.92557307, 0.35036498, 0.20382689, 0.57971994],
       [0.89626913, 0.13045303, 0.5897093 , 0.59899394]])

In [728]:
A[[0,2],:] = A[[2,0], :]

In [729]:
A

array([[0.92557307, 0.35036498, 0.20382689, 0.57971994],
       [0.51311101, 0.85904722, 0.46971943, 0.04818951],
       [0.38164107, 0.5969474 , 0.08686001, 0.92176969],
       [0.89626913, 0.13045303, 0.5897093 , 0.59899394]])

In [730]:
B =A
A+B

array([[1.85114613, 0.70072995, 0.40765379, 1.15943989],
       [1.02622201, 1.71809444, 0.93943887, 0.09637901],
       [0.76328214, 1.19389479, 0.17372001, 1.84353939],
       [1.79253826, 0.26090606, 1.1794186 , 1.19798789]])

In [731]:
#level 1 
for i in range(0,N):
    for j in range(i+1,N):
        A[j,:] = A[j,:] - A[j,i]/A[i,i]*A[i,:]
A

array([[ 9.25573066e-01,  3.50364975e-01,  2.03826894e-01,
         5.79719945e-01],
       [ 0.00000000e+00,  6.64814987e-01,  3.56723685e-01,
        -2.73190506e-01],
       [ 0.00000000e+00, -5.55111512e-17, -2.39974536e-01,
         8.68671016e-01],
       [ 0.00000000e+00, -1.16674387e-16,  0.00000000e+00,
         1.77760778e+00]])

In [732]:
#level 2
A = A_old
for i in range(0,N):
    #find max
    pos_max = [i,i]
    valmax = abs(A[i,i])
    for j in range(i,N):
        for k in range(i,N):
            v = abs(A[j][k])
            if(v> valmax):
                pos_max = [j,k]
                valmax = v
    if(pos_max[1]!= i):
        A[:, [i,pos_max[1]]] =  A[:, [pos_max[1], i]]
    if(pos_max[0]!= i):
        A[[i,pos_max[0]], :] =  A[ [pos_max[0], i], :]       
    for j in range(i+1,N):
        A[j,:] = A[j,:] - (A[j,i]/A[i,i])*A[i,:]

In [733]:
A

array([[ 1.77760778e+00,  0.00000000e+00, -1.16674387e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  9.25573066e-01,  3.50364975e-01,
         2.03826894e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.64814987e-01,
         3.56723685e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.39974536e-01]])

In [734]:
#level 3 : luu lai xoay hang, xoay cot, action_by_time
pivot_row = np.zeros(N)
pivot_col = np.zeros(N)
action_by_time = np.zeros((N,N))

A = A_old
for i in range(0,N):
    #find max
    pos_max = [i,i]
    valmax = abs(A[i,i])
    for j in range(i,N):
        for k in range(i,N):
            v = abs(A[j][k])
            if(v> valmax):
                pos_max = [j,k]
                valmax = v
    pivot_row[i] = int(pos_max[0])
    pivot_col[i] = int(pos_max[1])
    if(pos_max[1]!= i):
        A[:, [i,pos_max[1]]] =  A[:, [pos_max[1], i]]
    if(pos_max[0]!= i):
        A[[i,pos_max[0]], :] =  A[ [pos_max[0], i], :]       
    for j in range(i+1,N):
        A[j,:] = A[j,:] - (A[j,i]/A[i,i])*A[i,:]
        action_by_time[j,i] = (A[j,i]/A[i,i])

In [735]:
for i in range(N-1,-1,-1):
    A[i] = A[i]/A[i,i]
    action_by_time[i,i] = A[i,i]
    for j in range(i-1,-1,-1):
        A[j] = A[j] - A[j,i]*A[i]    
        action_by_time[j,i] = A[j,i]
A

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-0., -0., -0.,  1.]])

In [736]:
index_x = np.zeros(N)
for i in range(1,N):
    index_x[i] = int(i)
#index_x[[1,2] ]= index_x[[2,1]]
index_x

array([0., 1., 2., 3.])

In [737]:
b = np.random.rand(N)
b_old = b
for i in range(0,N):
    index_x[[i, int(pivot_col[i])]] = index_x[[int(pivot_col[i]), i]]
    b[[i, int(pivot_row[i])] ] = b[[int(pivot_row[i]), i]]
    for j in range(i+1,N):
        b[j] = b[j] - action_by_time[j,i]*b[i]

for i in range(N-1,-1,-1):
    b[j] = b[j]/ action_by_time[i,i]
    for j in range(i-1,-1,-1):
         b[j] = b[j] - action_by_time[j,i]*b[i]

x = np.zeros(N)
for i in range(0,N):
    x[int(index_x[i])] = b[i]


In [740]:
A_old.dot(x) - b_old

array([0., 0., 0., 0.])